import { FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Navigate, useNavigate, useSearchParams } from '../router'
import { CloudCog, KeyRound, LockKeyhole, Terminal } from 'lucide-react'
import { api } from '../api'
import { Button } from '../components/ui'
import type { User } from '../App'

export default function LoginPage(){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [params]=useSearchParams();const navigate=useNavigate();const queryClient=useQueryClient();const status=useQuery({queryKey:['auth-status'],queryFn:()=>api.get<{initialized:boolean}>('/auth/status')});const me=useQuery({queryKey:['me'],queryFn:()=>api.get<User>('/me'),retry:false});const login=useMutation({mutationFn:()=>api.post<{user:User;csrfToken:string}>('/auth/login',{username,password}),onSuccess:({user})=>{queryClient.setQueryData(['me'],user);const requested=params.get('returnTo')||'/';try{const target=new URL(requested,window.location.origin);if(target.origin===window.location.origin){window.location.assign(target.href);return}}catch{}navigate('/',{replace:true})}});if(me.data)return <Navigate to="/" replace/>;const submit=(event:FormEvent)=>{event.preventDefault();login.mutate()};return <main className="login-page"><div className="login-atmosphere" aria-hidden><span/><span/><span/></div><section className="login-card" aria-labelledby="login-heading"><div className="login-brand"><span className="brand__mark"><CloudCog aria-hidden/></span><div><strong>Asgard</strong><small>Small clouds, close to home.</small></div></div><div className="login-copy"><p className="eyebrow">CONTROL PLANE</p><h1 id="login-heading">Welcome back</h1><p>Sign in to manage your projects, releases, and the containers beneath them.</p></div>{status.data&&!status.data.initialized?<div className="bootstrap-card"><Terminal aria-hidden/><div><strong>Create the first administrator</strong><p>Run this once inside the control-plane container:</p><code>docker compose exec asgard asgard admin create --username ege</code></div></div>:<form onSubmit={submit}><label htmlFor="username">Username</label><div className="field-with-icon"><KeyRound aria-hidden/><input id="username" name="username" autoComplete="username" required autoFocus value={username} onChange={e=>setUsername(e.target.value)}/></div><label htmlFor="password">Password</label><div className="field-with-icon"><LockKeyhole aria-hidden/><input id="password" name="password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></div>{login.error?<p className="form-error" role="alert">{login.error.message}</p>:null}<Button type="submit" busy={login.isPending}>Sign in</Button></form>}<footer><LockKeyhole aria-hidden/> Password-protected · encrypted session · single administrator</footer></section></main>}
