import type { PropsWithChildren, ReactNode } from 'react'
import { AlertCircle, CheckCircle2, Circle, LoaderCircle } from 'lucide-react'

export function Button({children,variant='primary',busy=false,...props}:PropsWithChildren<React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger';busy?:boolean}>){return <button className={`button button--${variant}`} {...props} disabled={busy||props.disabled}>{busy?<LoaderCircle className="spin" aria-hidden/>:null}<span>{children}</span></button>}
export function IconButton({label,children,...props}:PropsWithChildren<React.ButtonHTMLAttributes<HTMLButtonElement>&{label:string}>){return <button className="icon-button" aria-label={label} title={label} {...props}>{children}</button>}
export function Status({value}:{value?:string}){const state=(value||'unknown').toLowerCase();const good=['healthy','running','succeeded','ready','active','connected','online'].includes(state);const bad=['failed','unhealthy','dead','error','missing','disconnected'].includes(state);const pending=['queued','deploying','starting','pending'].includes(state);const Icon=good?CheckCircle2:bad?AlertCircle:pending?LoaderCircle:Circle;return <span className={`status status--${good?'good':bad?'bad':pending?'pending':'neutral'}`}><Icon className={pending?'spin':''} aria-hidden/>{state.replaceAll('_',' ')}</span>}
export function EmptyState({icon,title,children,action}:{icon:ReactNode;title:string;children:ReactNode;action?:ReactNode}){return <div className="empty-state"><div className="empty-state__icon">{icon}</div><h2>{title}</h2><p>{children}</p>{action}</div>}
export function Skeleton({height=120}:{height?:number}){return <div className="skeleton" style={{height}} aria-hidden/>}
export function ErrorState({error}:{error:unknown}){return <div className="alert alert--error" role="alert"><AlertCircle aria-hidden/><div><strong>Couldn’t load this view</strong><p>{error instanceof Error?error.message:'An unexpected error occurred.'}</p></div></div>}
export function PageHeader({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <header className="page-header"><div>{eyebrow?<p className="eyebrow">{eyebrow}</p>:null}<h1>{title}</h1>{description?<p>{description}</p>:null}</div>{actions?<div className="page-header__actions">{actions}</div>:null}</header>}
export function Metric({label,value,detail}:{label:string;value:string;detail?:string}){return <div className="metric"><p>{label}</p><strong>{value}</strong>{detail?<span>{detail}</span>:null}</div>}
export const formatBytes=(value?:number)=>{if(!value||value<0)return '0 B';const units=['B','KB','MB','GB','TB'];const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return `${(value/1024**i).toFixed(i<2?0:1)} ${units[i]}`}
export const formatDate=(value?:string)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'
export const percent=(value?:number)=>`${(value??0).toFixed(1)}%`
